version: '3'

services:
  api:
    image: node:18
    working_dir: /app/api
    command: yarn start:dev
    volumes:
      - '.:/app'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bibcnrs?schema=public
    depends_on:
      - db

  front:
    image: node:18
    working_dir: /app/front
    command: yarn dev
    volumes:
      - '.:/app'
    environment:
      - VITE_API_URL=http://api:3001

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bibcnrs

  e2e:
    image: cypress/included:10.3.1-typescript
    working_dir: /app/front
    environment:
      - CYPRESS_baseUrl=http://front:3000
    depends_on:
      - front
    volumes:
      - .:/app
