version: '3'

services:
  api:
    image: node:18
    working_dir: /app/api
    command: yarn start:dev
    volumes:
      - '.:/app'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3001:3001'
    depends_on:
      - db

  front:
    image: node:18
    working_dir: /app/front
    command: yarn dev
    volumes:
      - '.:/app'
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - '3000:3000'

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
