version: '3'

services:
  api:
    image: node:18
    working_dir: /app/api
    command: yarn start:dev
    volumes:
      - '.:/app'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - EBSCO_API_URL=${EBSCO_API_URL}
      - INSHS_USER_ID=${INSHS_USER_ID}
      - INSHS_PASSWORD=${INSHS_PASSWORD}
      - INSHS_PROFILE=${INSHS_PROFILE}
    ports:
      - '3002:3001'
    # depends_on:
    #   - db

  front:
    image: node:18
    working_dir: /app/front
    command: yarn dev
    volumes:
      - '.:/app'
    environment:
      - API_URL=${API_URL}
    ports:
      - '3000:3000'
      - '8002:8002'

  # db:
  #   image: postgres:14
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRES_DB=${DATABASE_NAME}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
